<a href="https://colab.research.google.com/github/np03cs4a240386-prog/Concepts-and-Technologies-of-AI/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem-1

1.

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
empty_array



array([[1.07047573e-315, 0.00000000e+000],
       [2.12199579e-314, 5.30886346e+180]])

2.

In [ ]:
ones_array = np.ones((4, 2))
ones_array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3.

In [ ]:
full_array = np.full((3, 3), fill_value=7)
full_array


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4.

In [ ]:
given_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_like_array = np.zeros_like(given_array)
zeros_like_array


array([[0, 0, 0],
       [0, 0, 0]])

5.

In [ ]:
ones_like_array = np.ones_like(given_array)
ones_like_array


array([[1, 1, 1],
       [1, 1, 1]])

6.

In [ ]:
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
np_array


array([1, 2, 3, 4])

Problem 2


In [ ]:
import numpy as np

arr1 = np.arange(10, 50)
arr1


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
arr2 = np.arange(9).reshape(3, 3)
arr2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
identity = np.eye(3)
identity


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
random_arr = np.random.random(30)
mean_value = random_arr.mean()

random_arr, mean_value



(array([0.22748357, 0.7150374 , 0.83821042, 0.34916665, 0.80115866,
        0.54308996, 0.583841  , 0.52897013, 0.59880515, 0.35481778,
        0.18013814, 0.09952993, 0.45850461, 0.71815764, 0.93973102,
        0.77274568, 0.06918872, 0.64434812, 0.28385016, 0.29658947,
        0.56332182, 0.53175148, 0.24699276, 0.78394134, 0.65541285,
        0.67633268, 0.65164774, 0.65396011, 0.46215809, 0.20874959]),
 np.float64(0.5145877559145662))

In [ ]:
rand_matrix = np.random.random((10, 10))
min_val = rand_matrix.min()
max_val = rand_matrix.max()

min_val, max_val


(np.float64(0.009813098956349964), np.float64(0.997100025986742))

In [ ]:
arr3 = np.zeros(10)
arr3[4] = 1
arr3


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
arr[::-1]


array([0, 4, 0, 0, 2, 1])

In [ ]:
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
border


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
checker = np.zeros((8, 8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem3

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
add_xy = x + y
add_xy


array([[ 6,  8],
       [10, 13]])

In [ ]:
sub_xy = x - y
sub_xy


array([[-4, -4],
       [-4, -3]])

In [ ]:
mul_x = x * 3
mul_x


array([[ 3,  6],
       [ 9, 15]])

In [ ]:
sq_x = x ** 2
sq_x


array([[ 1,  4],
       [ 9, 25]])

In [ ]:
dot_vw = np.dot(v, w)
dot_vw
dot_xv = np.dot(x, v)
dot_xv
dot_xy = np.dot(x, y)
dot_xy



array([[19, 22],
       [50, 58]])

In [ ]:
concat_xy_row = np.concatenate((x, y), axis=0)
concat_xy_row


array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((x, v))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem4

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
identity_check



array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

AB, BA, AB == BA  # Shows AB and BA are not equal


(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]),
 array([[False, False],
        [False, False]]))

In [ ]:
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)

AB_T, B_T_A_T, np.allclose(AB_T, B_T_A_T)  # True if they are equal


(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]),
 True)

In [ ]:
# Coefficient matrix
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

# Constant vector
const = np.array([-1, -3, 9])
solution = np.linalg.solve(coeff, const)
solution


array([ 2.,  1., -2.])

In [ ]:
coeff_inv = np.linalg.inv(coeff)
solution_inv = np.dot(coeff_inv, const)
solution_inv


array([ 2.,  1., -2.])